// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mav_common.proto
// Original file comments:
// ------------------------------------------------------------------------------
//
// FILE    :mav_common.proto
// MODULE  :5G RAN
// DATE    :2019/10/22  14:08:24
// AUTHOR  :Fisher Yu
//
// ------------------------------------------------------------------------------
//
// FILE DESCRIPTION
//
// Describe here
//
// ------------------------------------------------------------------------------
//
// Copyright 2006-2019, Mavenir Systems Ltd.
// ALL RIGHTS RESERVED
//
// License to copy, use or disseminate this computer program,
// whether in part or in whole are expressly forbidden.
// ------------------------------------------------------------------------------
// Change Log(Cursor at here when add new log)
// ------------------------------------------------------------------------------
// DATE    :2019/10/22  14:08:24
// AUTHOR  :Fisher Yu
// DESCRIP :Created
// ------------------------------------------------------------------------------
//
#ifndef GRPC_mav_5fcommon_2eproto__INCLUDED
#define GRPC_mav_5fcommon_2eproto__INCLUDED

#include "mav_common.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace MavCommonAdaptor {

}  // namespace MavCommonAdaptor


#endif  // GRPC_mav_5fcommon_2eproto__INCLUDED
